apiVersion: v1
kind: Service
metadata:
  name:  "jenkins-master-service"
  namespace: "jenkins"
spec:
  selector:
    app:  "jenkins-master"
  type:  NodePort
  ports:
  - name: http-port
    nodePort: 30105
    port:  80
    targetPort:  8080
  - name: jnlp
    port: 50000
    targetPort: 50000
    nodePort: 30106